#!/bin/bash

echo "DOCUMENTATIOIN: https://docs.anbox.io/  or https://dev.to/sbellone/how-to-install-anbox-on-debian-1hjd"
echo "-------------------------------------------------------------------------------------"
echo "Try running $  anbox session-manager"
echo "If you get an error download image from https://build.anbox.io/ "
echo "use $ $ sudo mv ~/Downloads/android_amd64.img /var/lib/anbox/android.img "
echo "The above command is dependent on the name n location of the image"
echo "-------------------------------------------------------------------------------------"
echo "at this point, we restart anbox"
echo "$ sudo service anbox-container-manager restart"
echo "then run anbox. Desktop launcher can also do this: "
echo "anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity"
echo "-------------------------------------------------------------------------------------"
echo "To be able to install apps: "
echo "$ sudo apt install android-tools-adb"
echo "You now have everything needed to install new applications:"
echo "example"
echo " Download F-Droid: $ wget https://f-droid.org/F-Droid.apk "
echo "Install the apk: $ adb install F-Droid.apk"